#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'erlang'

cookbook 'chicagoboss',
  :git => 'https://github.com/thoward/chicagoboss-cookbook'
  
